### ISSUE TITLE
Broken build - "stdin" is not exported by unenv

### ISSUE THREAD

**Issue by Mehdi-Hp** [nuxt/icon#269]
Not sure if it's directly from @nuxt/icon or a dependency breaking change, but `build` breaks as soon as you add `@nuxt/icon` to modules. `develop` works okay.

Downgrading `unenv` or using the nightly version didn't help.

**To reproduce:**
1. `pnpx nuxthub init test-app`
2. `pnpx nuxi module add icon`
3. `pnpm build`

**Logs:**
```
[nitro 3:07:35 PM]  ERROR  RollupError: node_modules/.cache/nuxt/.nuxt/dist/server/_nuxt/prompt-BuYSwD7c.js (1:9): "stdin" is not exported by "node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/process/index.mjs", imported by "node_modules/.cache/nuxt/.nuxt/dist/server/_nuxt/prompt-BuYSwD7c.js".


1: import { stdin, stdout } from "node:process";
            ^
2: import f from "node:readline";
3: import { WriteStream } from "node:tty";


[3:07:35 PM]  ERROR  node_modules/.cache/nuxt/.nuxt/dist/server/_nuxt/prompt-BuYSwD7c.js (1:9): "stdin" is not exported by "node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/process/index.mjs", imported by "node_modules/.cache/nuxt/.nuxt/dist/server/_nuxt/prompt-BuYSwD7c.js".

  at getRollupError (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
  at error (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
  at Module.error (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:13971:16)
  at Module.traceVariable (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:14419:29)
  at ModuleScope.findVariable (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:12121:39)
  at ChildScope.findVariable (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
  at ClassBodyScope.findVariable (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
  at ChildScope.findVariable (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
  at ChildScope.findVariable (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
  at FunctionScope.findVariable (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
  at Identifier.bind (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:6941:40)
  at AssignmentPattern.bind (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:4808:23)
  at Property.bind (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:4808:23)
  at ObjectPattern.bind (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:4804:28)
  at FunctionExpression.bind (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:4804:28)
  at MethodDefinition.bind (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:4808:23)
  at ClassBody.bind (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:4804:28)
  at ClassDeclaration.bind (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:4808:23)
  at Program.bind (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:4804:28)
  at Module.bindReferences (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:13950:18)
  at Graph.sortModules (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20201:20)
  at Graph.build (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20105:14)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  at async node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20751:13
  at async catchUnfinishedHookActions (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20258:16)
  at async rollupInternal (node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20746:5)
  at async _build (node_modules/.pnpm/nitropack@2.9.7_@opentelemetry+api@1.9.0_encoding@0.1.13_magicast@0.3.5_webpack-sources@3.2.3/node_modules/nitropack/dist/nitro.mjs:2633:20)
  at async node_modules/.pnpm/nuxt@3.13.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.9_encoding@0.1.1_ybhcnuqrdhnlo4pjzrhb752cba/node_modules/nuxt/dist/index.mjs:3630:5
  at async build (node_modules/.pnpm/nuxt@3.13.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.9_encoding@0.1.1_ybhcnuqrdhnlo4pjzrhb752cba/node_modules/nuxt/dist/index.mjs:5778:3)
  at async Object.run (node_modules/.pnpm/nuxi@3.13.2/node_modules/nuxi/dist/chunks/build.mjs:102:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.13.2/node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.13.2/node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.13.2/node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1777:7)
```

---
- Operating System: Darwin
- Node Version:     v22.9.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    -
- Package Manager:  pnpm@9.11.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

**Comment by arnauddoub** [comment]
I have the same problem but it seems to be linked to the Cloudflare preset

**Comment by Mehdi-Hp** [comment]
Any suggestions on what I should downgrade for now? I tried downgrading `unenv` and `@nuxthub/core`, but no luck.

**Comment by miqlangelo** [comment]
I have recently encountered the same problem when the Nitro presets are set on cloudflare-pages. If I remove the Nuxthub module, I can build my project without any issues. I'm using Nuxt UI without integrating any extra @nuxt/icon.

With npm, I can build the application as usual.

It's strange that I only have this problem in new projects. I can still build old projects with Hub/UI error-free using pnpm. However, when I copy everything from those into a new application, I get the "stdin is not exported" error again.

node: 20.18.0
pnpm: 9.12.1
nuxt: 3.13.2

**Comment by Barnabas** [comment]
Sadly, adding an `.npmrc` file with `shamefully-hoist = true` seems to fix it. 

Found via: https://github.com/harlan-zw/nuxt-seo/issues/218#issuecomment-2351823567

**Comment by Mehdi-Hp** [comment]
This just got fixed in the latest version of `@nuxthub/core` 🎊

**Comment by antfu** [comment]
Consider this get fixed. If this occurs again, please create a new issue with a minimal reproduction, thanks!
