### ISSUE TITLE
Nuxt module should be a function: nuxt-icon

### ISSUE THREAD

**Issue by KhalilAMater** [nuxt/icon#329]
I encountered an error when running npm run build in my Nuxt 3 project. The error message states:

ERROR Nuxt module should be a function: nuxt-icon

This issue happens while trying to build the project, even after installing the latest version of nuxt-icon. The versions of the dependencies in my project are as follows:

Nuxt Version: 3.14.159
Node Version: v18.20.4
nuxt-icon Version: ^0.5.0
CLI Version: 3.15.0
Nitro Version: 2.10.4

I have tried reinstalling the nuxt-icon module and performing a cleanup using npx nuxi cleanup, but the issue persists.

Steps to reproduce:

Set up a Nuxt 3 project.
Install nuxt-icon (version ^0.5.0).
Run npm run build.

The error occurs.
Expected behavior: The build process should complete successfully without any errors related to the nuxt-icon module.

Additional context:

I am using yarn as the package manager.
I have also checked that my nuxt.config.ts is properly configured to use nuxt-icon.
How to resolve:

I have tried solutions such as cleaning up the cache and reinstalling dependencies, but the issue persists.
The issue seems to be related to the nuxt-icon module not being recognized as a function by Nuxt.

this is my package.json file

{
"name": "store",
"private": true,
"type": "module",
"scripts": {
"build": "nuxt build",
"dev": "nuxt dev",
"generate": "nuxt generate",
"preview": "nuxt preview",
"postinstall": "nuxt prepare",
"getLang": "node ./scripts/getLang.js"
},
"devDependencies": {
"@nuxt/devtools": "latest",
"@nuxtjs/i18n": "^8.0.0-rc.4",
"@nuxtjs/supabase": "^0.3.0",
"nuxt": "^3.7.2",
"nuxt-gtag": "^1.1.2",
"nuxt-icon": "^0.5.0"
},
"dependencies": {
"@fortawesome/fontawesome-svg-core": "^6.4.2",
"@fortawesome/free-brands-svg-icons": "^6.4.2",
"@fortawesome/vue-fontawesome": "^3.0.3",
"@vuelidate/core": "^2.0.3",
"@vuelidate/validators": "^2.0.4",
"@vueuse/nuxt": "^10.7.1",
"axios": "^1.5.1",
"click-outside-vue3": "^4.0.1",
"firebase": "^10.12.2",
"nuxt-swiper": "^1.2.2",
"nuxt3-meta-pixel": "^1.0.9",
"vue-slider-component": "^4.1.0-beta.7"
}
}

after npm run build
npm run build

build
nuxt build

Nuxt 3.14.1592 with Nitro 2.10.4 9:10:37 AM
ℹ Using 2024-04-03 as fallback compatibility date. 9:10:38 AM

ERROR Nuxt module should be a function: nuxt-icon 9:10:39 AM

at loadNuxtModuleInstance (/home//nodevenv/public_html/landingpage/18/lib/node_modules/@nuxt/kit/dist/index.mjs:2466:11)
at async installModule (/home//nodevenv/public_html/landingpage/18/lib/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
at async initNuxt (/home//nodevenv/public_html/landingpage/18/lib/node_modules/nuxt/dist/index.mjs:4684:5)
at async loadNuxt (/home//nodevenv/public_html/landingpage/18/lib/node_modules/nuxt/dist/index.mjs:4854:5)
at async Module.loadNuxt (/home//nodevenv/public_html/landingpage/18/lib/node_modules/@nuxt/kit/dist/index.mjs:2633:19)
at async Object.run (/home//nodevenv/public_html/landingpage/18/lib/node_modules/nuxi/dist/chunks/build.mjs:76:18)
at async runCommand$1 (/home//nodevenv/public_html/landingpage/18/lib/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1643:16)
at async runCommand$1 (/home//nodevenv/public_html/landingpage/18/lib/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1634:11)
at async runMain$1 (/home//nodevenv/public_html/landingpage/18/lib/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1772:7)

ERROR Nuxt module should be a function: nuxt-icon

i am use the cpanel Setup nod js App
and ssh to run

**Comment by cyberalien** [comment]
Install `@nuxt/icon`, not `nuxt-icon`.

**Comment by antfu** [comment]
You already created the same issue #328, please don't do that.
